### ISSUE TITLE
Ready?

### ISSUE THREAD

**Issue by hype3** [johanmalm/labwc-tweaks#1]
Hi.

When will this be ready for regular use?
Or is it stable enough for testing?

**Comment by johanmalm** [comment]
> When will this be ready for regular use?

This is no real plan for it - and no Acceptance Criteria. I merely it wrote it to help me to change themes quickly to make sure that they render properly on labwc.
In terms of taking it further I think my preference is to only include options that users are likely to use regularly - rather than trying to cover every tweak going.

> Or is it stable enough for testing?
Yes - it should compile and run fine. If it segfaults or misbehaves, let me know.
It's not really been written like 'production code' to cope with all situations. For example, I just realized that it crashes if ~/.config/labwc/rc.xml is missing (have just pushed a fix), so that gives us flavor of its maturity :smile:

**Comment by hype3** [comment]
Ok. I compiled it and it doing it's job.
I use Labwc now as my daily driver and found some bugs that I posted.
Anyway I really like Labwc and keep up the good work!

**Comment by johanmalm** [comment]
> I use Labwc now as my daily driver and found some bugs that I posted.

Awesome.

I've updated the README to reflect the state of this app
